export const attractions = 

[
{
  name: "RK Beach",
  slug: "rk-beach",
  category: "Beach",
  shortDescription: "Vizag's most loved city beach with sunrise views and a lively promenade.",
  description: "Ramakrishna Beach is one of the most iconic attractions in Visakhapatnam. Located along Beach Road, it is known for its scenic coastline, sunrise views, food stalls, walking promenade, museums, and nearby landmarks. The beach is a popular destination for locals and tourists looking to relax by the Bay of Bengal.",
  location: "Beach Road",
  address: "RK Beach, Beach Road, Visakhapatnam, Andhra Pradesh 530002",
  timings: "5:00 AM - 10:00 PM",
  entryFee: "Free",
  bestTimeToVisit: "October - March",
  images: [
    "https://www.shutterstock.com/image-photo/november-132018-visakhapatnam-india-top-260nw-1260153169.jpg"
  ],
  mapUrl: "https://maps.google.com/?q=17.7149,83.3237",
  latitude: 17.7149,
  longitude: 83.3237,
  highlights: [
    "Sunrise views",
    "Beach promenade",
    "Food stalls",
    "Nearby museums"
  ],
  averageRating: 4.5,
  reviewCount: 0,
  isFeatured: true
},
{
    name: "Rushikonda Beach",
    slug: "rushikonda-beach",
    category: "Beach",
    shortDescription: "Vizag's most popular beach known for water sports and golden sands.",
    description: "Rushikonda Beach is one of the most visited beaches in Visakhapatnam, famous for its clean shoreline, water sports activities, and scenic surroundings. The beach offers swimming, jet skiing, and breathtaking sunrise views.",
    location: "Rushikonda",
    address: "Rushikonda Beach Road, Visakhapatnam, Andhra Pradesh 530045",
    timings: "5:00 AM - 8:00 PM",
    entryFee: "Free",
    bestTimeToVisit: "October - March",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn1SQuOKKk6AwBZ5KvYh-5uCnTUJBB5D1wRJUmTBpevg&s"],
    mapUrl: "https://maps.google.com/?q=Rushikonda+Beach+Visakhapatnam",
    latitude: 17.7828,
    longitude: 83.3853,
    highlights: ["Water sports", "Golden sand", "Swimming", "Sunrise views"],
    averageRating: 4.6,
    reviewCount: 0,
    isFeatured: true
  },

  {
    name: "Yarada Beach",
    slug: "yarada-beach",
    category: "Beach",
    shortDescription: "A secluded beach surrounded by hills and the Bay of Bengal.",
    description: "Yarada Beach is a pristine and less crowded beach known for its scenic beauty. Surrounded by lush hills on three sides and the sea on the fourth, it offers a peaceful escape from city life.",
    location: "Yarada",
    address: "Yarada Village, Visakhapatnam, Andhra Pradesh",
    timings: "6:00 AM - 6:30 PM",
    entryFee: "Free",
    bestTimeToVisit: "November - February",
    images: ["https://thumbs.dreamstime.com/b/yarada-beach-sunny-day-andhra-pradesh-close-to-visakhapatnam-183669376.jpg"],
    mapUrl: "https://maps.google.com/?q=Yarada+Beach+Visakhapatnam",
    latitude: 17.6584,
    longitude: 83.2512,
    highlights: ["Secluded beach", "Hill views", "Photography", "Sunsets"],
    averageRating: 4.7,
    reviewCount: 0,
    isFeatured: true
  },

  {
    name: "Bheemunipatnam Beach",
    slug: "bheemunipatnam-beach",
    category: "Beach",
    shortDescription: "Historic beach town where the Gosthani River meets the sea.",
    description: "Bheemunipatnam Beach, popularly called Bheemili Beach, combines natural beauty with colonial history. Visitors can enjoy the wide shoreline, river-sea confluence, and historic Dutch-era landmarks.",
    location: "Bheemunipatnam",
    address: "Bheemunipatnam, Visakhapatnam, Andhra Pradesh 531163",
    timings: "5:00 AM - 8:00 PM",
    entryFee: "Free",
    bestTimeToVisit: "October - March",
    images: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/f0/63/83/caption.jpg?w=900&h=500&s=1"],
    mapUrl: "https://maps.google.com/?q=Bheemunipatnam+Beach",
    latitude: 17.8905,
    longitude: 83.4528,
    highlights: ["Historic town", "River meets sea", "Dutch Cemetery", "Sunsets"],
    averageRating: 4.5,
    reviewCount: 0,
    isFeatured: true
  },
{
  name: "Simhachalam Temple",
  slug: "simhachalam-temple",
  category: "Temple",
  shortDescription: "Famous temple dedicated to Lord Varaha Lakshmi Narasimha.",
  description: "Simhachalam Temple is one of the most important Hindu temples in Andhra Pradesh, known for its architecture and spiritual significance.",
  location: "Simhachalam",
  address: "Simhachalam, Visakhapatnam, Andhra Pradesh",
  timings: "7:00 AM - 8:30 PM",
  entryFee: "Free",
  bestTimeToVisit: "Morning",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyGQxKsJfiyHGRLEobZrRJZueJiAw2zk1Ks1an21jKE18nSOBo32verD34&s=10"],
  mapUrl: "https://maps.google.com/?q=Simhachalam+Temple",
  latitude: 17.7665,
  longitude: 83.2508,
  highlights: ["Ancient architecture", "Spiritual center", "Festivals"],
  averageRating: 4.9,
  reviewCount: 0,
  isFeatured: true
},
{
  name: "Kanaka Mahalakshmi Temple",
  slug: "kanaka-mahalakshmi-temple",
  category: "Temple",
  shortDescription: "One of the most revered temples in Visakhapatnam.",
  description: "Dedicated to Goddess Kanaka Mahalakshmi, this temple attracts thousands of devotees every year.",
  location: "Burujupeta",
  address: "Burujupeta, Visakhapatnam, Andhra Pradesh",
  timings: "5:00 AM - 9:00 PM",
  entryFee: "Free",
  bestTimeToVisit: "Morning",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOp3jbsAYA0EDr1RhGdJp0dfrmqEgPFFK5JsW9KZtJQ2ah8XSWTRcMhTLi&s=10"],
  mapUrl: "https://maps.google.com/?q=Kanaka+Mahalakshmi+Temple",
  latitude: 17.6868,
  longitude: 83.2185,
  highlights: ["Goddess temple", "Festivals", "City landmark"],
  averageRating: 4.8,
  reviewCount: 0,
  isFeatured: true
},
{
  name: "Sri Venkateswara Swamy Temple",
  slug: "sri-venkateswara-swamy-temple",
  category: "Temple",
  shortDescription: "Beautiful temple dedicated to Lord Venkateswara.",
  description: "A peaceful temple known for its spiritual atmosphere and traditional architecture.",
  location: "MVP Colony",
  address: "MVP Colony, Visakhapatnam, Andhra Pradesh",
  timings: "6:00 AM - 8:00 PM",
  entryFee: "Free",
  bestTimeToVisit: "Morning",
  images: ["https://s7ap1.scene7.com/is/image/incredibleindia/2-sri-venkateswara-swamy-vaari-temple-2-attr-hero?qlt=82&ts=1742151008949"],
  mapUrl: "https://maps.google.com/?q=Sri+Venkateswara+Swamy+Temple+Vizag",
  latitude: 17.7400,
  longitude: 83.3400,
  highlights: ["Peaceful atmosphere", "Architecture", "Religious events"],
  averageRating: 4.7,
  reviewCount: 0,
  isFeatured: false
},
{
  name: "ISKCON Temple Vizag",
  slug: "iskcon-temple-vizag",
  category: "Temple",
  shortDescription: "A spiritual center dedicated to Lord Krishna.",
  description: "ISKCON Temple offers devotional programs, bhajans, and a peaceful environment for visitors.",
  location: "Sagar Nagar",
  address: "Sagar Nagar, Visakhapatnam, Andhra Pradesh",
  timings: "4:30 AM - 8:30 PM",
  entryFee: "Free",
  bestTimeToVisit: "Evening",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsEgVkEoBNI4bxS2gt6OXKcH2J6fp2ut_jZhwXoXfZAclsgGH0NbEW6qt4&s=10"],
  mapUrl: "https://maps.google.com/?q=ISKCON+Temple+Vizag",
  latitude: 17.7700,
  longitude: 83.3700,
  highlights: ["Krishna worship", "Bhajans", "Spiritual programs"],
  averageRating: 4.8,
  reviewCount: 0,
  isFeatured: true
},
{
  name: "Sri Sampath Vinayagar Temple",
  slug: "sri-sampath-vinayagar-temple",
  category: "Temple",
  shortDescription: "Popular Lord Ganesha temple in the heart of Vizag.",
  description: "A famous temple visited by devotees seeking blessings from Lord Vinayaka.",
  location: "Asilmetta",
  address: "Asilmetta Junction, Visakhapatnam, Andhra Pradesh",
  timings: "5:30 AM - 9:00 PM",
  entryFee: "Free",
  bestTimeToVisit: "Morning",
  images: ["https://feeds.abplive.com/onecms/images/uploaded-images/2022/08/26/25e122bc4a75c6530eedf582eed8483f1661478175180233_original.jpg"],
  mapUrl: "https://maps.google.com/?q=Sampath+Vinayagar+Temple+Vizag",
  latitude: 17.7230,
  longitude: 83.3020,
  highlights: ["Lord Ganesha", "City center", "Devotional activities"],
  averageRating: 4.8,
  reviewCount: 0,
  isFeatured: true
},
{
  name: "Indira Gandhi Zoological Park",
  slug: "indira-gandhi-zoological-park",
  category: "Nature",
  shortDescription: "Large zoo surrounded by Eastern Ghats forests.",
  description: "One of India's largest zoological parks, home to tigers, lions, elephants, deer, and exotic birds.",
  location: "Kambalakonda",
  address: "Indira Gandhi Zoo Park, Visakhapatnam, Andhra Pradesh",
  timings: "9:00 AM - 5:00 PM",
  entryFee: "₹50",
  bestTimeToVisit: "Morning",
  images: ["https://www.yovizag.com/wp-content/uploads/2019/07/web-Indira-gandhi-zoo-park.webp"],
  mapUrl: "https://maps.google.com/?q=Indira+Gandhi+Zoo+Park+Vizag",
  latitude: 17.7685,
  longitude: 83.3532,
  highlights: ["Wildlife", "Nature Trails", "Photography"],
  averageRating: 4.4,
  reviewCount: 0,
  isFeatured: true
},

{
  name: "Kambalakonda Wildlife Sanctuary",
  slug: "kambalakonda-wildlife-sanctuary",
  category: "Nature",
  shortDescription: "Protected forest area rich in biodiversity.",
  description: "A natural green zone offering trekking, bird watching, and eco-tourism activities.",
  location: "Visakhapatnam",
  address: "Kambalakonda Wildlife Sanctuary, Andhra Pradesh",
  timings: "6:00 AM - 6:00 PM",
  entryFee: "₹20",
  bestTimeToVisit: "October to February",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSroUh79ZU89pyX3tLFeqbFgKiHkupaYQjmBVbP5EAGiJlgfliHidbTIyce&s=10"],
  mapUrl: "https://maps.google.com/?q=Kambalakonda+Wildlife+Sanctuary",
  latitude: 17.7854,
  longitude: 83.3512,
  highlights: ["Trekking", "Bird Watching", "Forest Views"],
  averageRating: 4.5,
  reviewCount: 0,
  isFeatured: true
},

{
  name: "Katiki Waterfalls",
  slug: "katiki-waterfalls",
  category: "Nature",
  shortDescription: "Beautiful waterfall near Borra Caves.",
  description: "A scenic waterfall surrounded by lush greenery and trekking trails.",
  location: "Araku",
  address: "Katiki Waterfalls, Visakhapatnam District",
  timings: "6:00 AM - 5:00 PM",
  entryFee: "Free",
  bestTimeToVisit: "Monsoon and Winter",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdedrEHEDJlS6h3xK5wCMig81KVOLaaZtzwalnuKqC6Es51pElFbSJq-0&s=10"],
  mapUrl: "https://maps.google.com/?q=Katiki+Waterfalls",
  latitude: 18.2634,
  longitude: 83.0372,
  highlights: ["Waterfall", "Trekking", "Photography"],
  averageRating: 4.5,
  reviewCount: 0,
  isFeatured: true
},

{
  name: "Chaparai Water Cascade",
  slug: "chaparai-water-cascade",
  category: "Nature",
  shortDescription: "Natural water stream and picnic spot near Araku.",
  description: "A popular destination where water flows over smooth rock formations.",
  location: "Araku Valley",
  address: "Chaparai, Araku Valley, Andhra Pradesh",
  timings: "8:00 AM - 6:00 PM",
  entryFee: "₹20",
  bestTimeToVisit: "October to February",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgNnTQ98Or-AMSkAc4ZC6xxJvn-3V2gq_EKXMN-sVJ6FT4Aox_VZyvsr8&s=10"],
  mapUrl: "https://maps.google.com/?q=Chaparai+Water+Cascade",
  latitude: 18.3145,
  longitude: 82.9198,
  highlights: ["Picnic Spot", "Nature", "Water Stream"],
  averageRating: 4.4,
  reviewCount: 0,
  isFeatured: true
},
{
  name: "Tribal Museum",
  slug: "tribal-museum-araku",
  category: "Museum",
  shortDescription: "Showcases tribal culture and traditions of Araku.",
  description: "Features tribal artifacts, handicrafts, costumes, and cultural exhibits.",
  location: "Araku Valley",
  address: "Araku Valley, Andhra Pradesh",
  timings: "10:00 AM - 6:00 PM",
  entryFee: "₹40",
  bestTimeToVisit: "Anytime",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYQBiDQb2FBgtbajMag1Cg_H8BK5dsa-NK40yl4CkP9Xaijae-GMxED64&s=10"],
  mapUrl: "https://maps.google.com/?q=Tribal+Museum+Araku",
  latitude: 18.3278,
  longitude: 82.8785,
  highlights: ["Tribal Culture", "Artifacts", "Handicrafts"],
  averageRating: 4.4,
  reviewCount: 0,
  isFeatured: true
},


{
  name: "INS Kursura Submarine Museum",
  slug: "ins-kursura-submarine-museum",
  category: "Museum",
  shortDescription: "India's first submarine museum located on RK Beach.",
  description: "A retired submarine converted into a museum showcasing naval history and life inside a submarine.",
  location: "RK Beach",
  address: "Beach Road, Visakhapatnam, Andhra Pradesh",
  timings: "2:00 PM - 8:30 PM",
  entryFee: "₹70",
  bestTimeToVisit: "Evening",
  images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTICzXqKgrY4TrwN478zY27b-A3f7DNCdlv_WQF0moUKCv_ViCXO0E-_4A&s=10"],
  mapUrl: "https://maps.google.com/?q=INS+Kursura+Submarine+Museum",
  latitude: 17.7176,
  longitude: 83.3305,
  highlights: ["Submarine tour", "Naval history", "Family attraction"],
  averageRating: 4.6,
  reviewCount: 0,
  isFeatured: true
},
{
  name: "TU 142 Aircraft Museum",
  slug: "tu-142-aircraft-museum",
  category: "Museum",
  shortDescription: "A unique aircraft museum featuring the legendary TU-142 aircraft.",
  description: "The museum showcases the history of Indian Naval Aviation through a decommissioned TU-142 aircraft.",
  location: "Beach Road",
  address: "RK Beach Road, Visakhapatnam, Andhra Pradesh",
  timings: "2:00 PM - 8:30 PM",
  entryFee: "₹70",
  bestTimeToVisit: "Evening",
  images: ["https://preview.redd.it/to-whoever-took-this-shot-v0-2gkoj44pjome1.jpeg?auto=webp&s=3b726b0e4d17b9d604b3e0d248bd0c0c94073786"],
  mapUrl: "https://maps.google.com/?q=TU+142+Aircraft+Museum",
  latitude: 17.7159,
  longitude: 83.3312,
  highlights: ["Aircraft tour", "Naval aviation", "Photography"],
  averageRating: 4.7,
  reviewCount: 0,
  isFeatured: true
},
{
  name: "Visakha Museum",
  slug: "visakha-museum",
  category: "Museum",
  shortDescription: "Museum displaying artifacts related to Vizag's history and culture.",
  description: "Visakha Museum exhibits historical documents, maritime artifacts, weapons, and cultural treasures of the region.",
  location: "Beach Road",
  address: "Beach Road, Visakhapatnam, Andhra Pradesh",
  timings: "10:00 AM - 5:00 PM",
  entryFee: "₹20",
  bestTimeToVisit: "Morning",
  images: ["https://s7ap1.scene7.com/is/image/incredibleindia/archaeological-museum-visakhapatnam-andhra-pradesh-3-attr-hero?qlt=82&ts=1742151130109"],
  mapUrl: "https://maps.google.com/?q=Visakha+Museum",
  latitude: 17.7203,
  longitude: 83.3335,
  highlights: ["Historical artifacts", "Local culture", "Maritime exhibits"],
  averageRating: 4.3,
  reviewCount: 0,
  isFeatured: false
},
{
    name: "VUDA Park",
    slug: "vuda-park",
    category: "Park",
    shortDescription: "Popular urban park on Beach Road with gardens, play areas, and walking tracks.",
    description: "VUDA Park is one of Visakhapatnam's most visited recreational parks, featuring landscaped gardens, children's play zones, jogging paths, and cultural events.",
    location: "Beach Road",
    address: "Beach Rd, Visakhapatnam, Andhra Pradesh",
    timings: "6:00 AM - 8:00 PM",
    entryFee: "₹20",
    bestTimeToVisit: "Morning and evening",
    images: ["https://vizagtourism.org.in/images/tourist-places/vuda-park-vizag/vuda-park-vizag-india-tourism-history.jpg"],
    mapUrl: "https://maps.google.com/?q=VUDA+Park+Visakhapatnam",
    latitude: 17.7235,
    longitude: 83.3315,
    highlights: ["Jogging track", "Children's play area", "Landscaped gardens"],
    averageRating: 4.4,
    reviewCount: 0,
    isFeatured: true

  },
  {
    name: "Tenneti Park",
    slug: "tenneti-park",
    category: "Park",
    shortDescription: "Scenic seaside park offering panoramic Bay of Bengal views.",
    description: "Tenneti Park is a beautifully maintained coastal park situated along the Vizag shoreline, known for sunset views, sea breeze, and photography spots.",
    location: "Jodugullapalem",
    address: "Tenneti Park, Beach Rd, Visakhapatnam, Andhra Pradesh",
    timings: "6:00 AM - 7:00 PM",
    entryFee: "Free",
    bestTimeToVisit: "Sunrise and sunset",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0JbNebPSOnv0ikQ0x_nWHGQvPBMwk_Q942yhzi9LZEw&s=10"],
    mapUrl: "https://maps.google.com/?q=Tenneti+Park+Visakhapatnam",
    latitude: 17.7468,
    longitude: 83.3435,
    highlights: ["Sea views", "Photography spot", "Sunset point"],
    averageRating: 4.5,
    reviewCount: 0,
    isFeatured: true
  },
  {
     name: "Kailasagiri Hill Park",
    slug: "kailasagiri-hill-park",
    category: "Park",
    shortDescription: "Hilltop park with iconic Shiva-Parvati statue and city views.",
    description: "Kailasagiri is a major tourist attraction featuring gardens, viewpoints, ropeway access, toy train rides, and stunning views of Visakhapatnam.",
    location: "Kailasagiri",
    address: "Kailasagiri, Visakhapatnam, Andhra Pradesh",
    timings: "10:00 AM - 8:00 PM",
    entryFee: "₹20",
    bestTimeToVisit: "Evening",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1PiQYO-zhvz52_Mng2rb42PDo7LhsgvACDNS5-WlRjw&s=10"],
    mapUrl: "https://maps.google.com/?q=Kailasagiri+Visakhapatnam",
    latitude: 17.7669,
    longitude: 83.3436,
    highlights: ["Shiva-Parvati statue", "Ropeway", "Toy train", "Viewpoint"],
    averageRating: 4.6,
    reviewCount: 0,
    isFeatured: true
  },
  {
     name: "Central Park",
    slug: "central-park-vizag",
    category: "Park",
    shortDescription: "Well-maintained city park with green lawns and walking paths.",
    description: "Central Park offers a relaxing environment for families and fitness enthusiasts with landscaped greenery and open spaces.",
    location: "Maddilapalem",
    address: "Maddilapalem, Visakhapatnam, Andhra Pradesh",
    timings: "5:30 AM - 8:30 PM",
    entryFee: "Free",
    bestTimeToVisit: "Morning",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ7Xbp__VQXv4hrEKuLit4_S_4H_fD_87tv0qFRiveXQ&s=10"],
    mapUrl: "https://maps.google.com/?q=Central+Park+Visakhapatnam",
    latitude: 17.7415,
    longitude: 83.3173,
    highlights: ["Walking track", "Green lawns", "Family outings"],
    averageRating: 4.2,
    reviewCount: 0,
    isFeatured: false

  },
  {
    name: "Kailasagiri",
    slug: "kailasagiri",
    category: "Park",
    shortDescription: "Hilltop park with panoramic sea and city views.",
    description: "Kailasagiri offers one of the best views of Vizag, with ropeway rides, viewpoints, gardens, and the famous Shiva-Parvati statue.",
    location: "Hilltop Road",
    address: "Kailasagiri, Visakhapatnam, Andhra Pradesh",
    timings: "10:00 AM - 8:00 PM",
    entryFee: "Nominal entry and ride charges",
    bestTimeToVisit: "Evening",
    images: ["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80"],
    mapUrl: "https://maps.google.com/?q=Kailasagiri+Visakhapatnam",
    latitude: 17.7486,
    longitude: 83.3427,
    highlights: ["Ropeway", "Toy train", "Sea viewpoint"],
    averageRating: 4.8,
    reviewCount: 0,
    isFeatured: true
  },
];

export const events = [
  {
    title: "Vizag Beach Walk Festival",
    slug: "vizag-beach-walk-festival",
    description: "A morning community walk with local food, music, and coastal clean-up activities.",
    venue: "RK Beach",
    startDate: new Date("2026-08-15T06:00:00.000Z"),
    endDate: new Date("2026-08-15T10:00:00.000Z"),
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    price: "Free",
    organizer: "Explore Vizag",
    category: "Spiritual"
  },
  {
    title: "Araku Coffee Weekend",
    slug: "araku-coffee-weekend",
    description: "Taste local coffee, meet growers, and enjoy a curated weekend itinerary.",
    venue: "Araku Valley",
    startDate: new Date("2026-09-05T04:30:00.000Z"),
    endDate: new Date("2026-09-06T14:30:00.000Z"),
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",
    price: "Paid",
    organizer: "Vizag Tourism Collective",
    category: "Cultural"
  }
];

export const blogs = [
  {
    title: "A Perfect Two-Day Vizag Itinerary",
    slug: "perfect-two-day-vizag-itinerary",
    excerpt: "Beach mornings, hilltop evenings, museums, temples, and a quick route plan.",
    content: "Start day one with RK Beach and the Submarine Museum, then spend sunset at Kailasagiri. On day two, plan Simhachalam Temple in the morning and Rushikonda Beach in the afternoon. Keep one relaxed meal on Beach Road and leave buffer time for traffic.",
    coverImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    tags: ["itinerary", "weekend", "vizag"]
  },
  {
    title: "Best Sunrise Spots in Visakhapatnam",
    slug: "best-sunrise-spots-in-visakhapatnam",
    excerpt: "Where to catch the softest morning light across the coastline.",
    content: "RK Beach, Tenneti Park, and Rushikonda are dependable sunrise choices. Arrive early, carry water, and choose weekdays when you want quieter frames.",
    coverImage: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
    tags: ["sunrise", "beach", "photography"]
  }
];
